const data = [{
        id: 9090,
        name: "Item1",
        price: 200,
        discount: 10,
        type: "fiction",
        img_url: "https://place-hold.it/40.jpg",
        count: 1,

    },
    {
        id: 9091,
        name: "Item2",
        price: 250,
        discount: 15,
        type: "literature",
        img_url: "https://place-hold.it/40.jpg",
        count: 1,
    },
    {
        id: 9092,
        name: "Item3",
        price: 320,
        discount: 5,
        type: "literature",
        img_url: "https://place-hold.it/40.jpg",
        count: 1,
    },
    {
        id: 9093,
        name: "Item4",
        price: 290,
        discount: 0,
        type: "thriller",
        img_url: "https://place-hold.it/40.jpg",
        count: 1,
    },
    {
        id: 9094,
        name: "Item5",
        price: 500,
        discount: 25,
        type: "thriller",
        img_url: "https://place-hold.it/40.jpg",
        count: 1,
    },
    {
        id: 9095,
        name: "Item6",
        price: 150,
        discount: 5,
        type: "literature",
        img_url: "https://place-hold.it/40.jpg",
        count: 1,
    },
    {
        id: 9096,
        name: "Item7",
        price: 700,
        discount: 22,
        type: "literature",
        img_url: "https://place-hold.it/40.jpg",
        count: 1,
    },
    {
        id: 9097,
        name: "Item8",
        price: 350,
        discount: 18,
        type: "fiction",
        img_url: "https://place-hold.it/40.jpg",
        count: 1,
    }
];

export default data;